# Change these first
owner: "Voucher-Game" # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: Vouchergame
    url: https://vouchergame.id
    assignees:
      - zaidanriski

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /monitor
  logoUrl: https://vouchergame.id/images/logo_new.png
  name: "Vouchergame Monitor"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
